name:                register-homeip-route53
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/register-homeip-route53#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - amazonka
  - amazonka-route53
  - typed-process
  - bytestring
  - lens
  - text
  - optparse-generic
  - string-conversions

executables:
  register-homeip-route53:
    source-dirs:      src
    main:             Main.hs
